server:
  port: 8090
  session-timeout: 60

spring.profiles.active: proddb
spring.profiles.include: mailon, whatsappon

---
spring:
  profiles: proddb
  datasource:
    url: ${SECRET_DB_URL}
    username: ${SECRET_DB_USERNAME}
    password: ${SECRET_DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        default_schema: ${SECRET_DB_SCHEMA}
        hibernate.show_sql: false
        format_sql: false

plataforma.whatsapp:
  url: ${WHATSAPP_URL}
  token: ${WHATSAPP_TOKEN}
  notificarSolicita: ${WHATSAPP_NOTIFICA_SOLICITA}
  kilometros: ${WHATSAPP_KILOMETROS}
  mensaje:
    ofrece: ${WHATSAPP_MENSAJE_OFRECE}
    solicita: ${WHATSAPP_MENSAJE_SOLICITA}

---

spring:
  profiles: localdb
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test_db
    username: sa
    password: jcll
  jpa:
    show-sql: false
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

plataforma.whatsapp:
  notificarSolicita: true
  kilometros: 10
  mensaje:
    ofrece: Hola %s encontramos que tu ayuda %s puede ser muy util para %s quien solicita %s puedes contactarlo en este numero %s
    solicita: Hola %s encontramos que tu solicitud %s puede ser atendida por %s quien ofrece %s puedes contactarlo en este numero %s

---
spring:
  profiles: mailon

mail:
  host: smtp.gmail.com
  port: 587
  username: ${SECRET_EMAIL_USERNAME}
  password: ${SECRET_EMAIL_PASSWORD}
  from.default: notificacion@plataformacovid19.mx
  to.default: notificacion@plataformacovid19.mx
  subject.default: Notificacion PMC
  transport.protocol: smtp
  debug: off
  smtp:
    auth: true
    starttls.enable: true
