server:
  port: 8090
  session-timeout: 60

spring.profiles.active: proddb
spring.profiles.include: mailoff

---
spring:
  profiles: proddb
  datasource:
    url: ${SECRET_DB_URL}
    username: ${SECRET_DB_USERNAME}
    password: ${SECRET_DB_PASSWORD}
  jpa:
    hibernate.ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        default_schema: ${SECRET_DB_SCHEMA}
        hibernate.show_sql: false
        format_sql: false

---

spring:
  profiles: localdb
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/test_db
    username: sa
    password: jcll
  jpa:
    show-sql: false
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

plataforma.url.confirm.token: http://localhost:8090/confirm

---
spring:
  profiles: mailon

mail:
  host: smtp.gmail.com
  port: 587
  username: ${SECRET_EMAIL_USERNAME}
  password: ${SECRET_EMAIL_PASSWORD}
  from.default: notificacion@plataformacovid19.mx
  to.default: notificacion@plataformacovid19.mx
  subject.default: Notificacion PMC
  transport.protocol: smtp
  debug: off
  smtp:
    auth: true
    starttls.enable: true
